---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    state: present
    cft_url: "https://s3.amazonaws.com/netscaler-cft-templates/cft-ha-3-nic-mz.template" # DO NOT change
    region: "" # Specify AWS Region
    debug_verbosity: 3 # use playbook with -vvv option to get the log message
    cft_params:
      # Citrix ADC Image
      CitrixADCImageID: "" # OPTIONAL. AMI ID of Citrix ADC to be provisioned. If left empty, "Citrix ADC VPX - Customer Licensed Version 12.1-50.28 (https://aws.amazon.com/marketplace/pp/B00AA01BOE)" is provisioned by default

      # Virtual Private Network Configuration
      VpcId: vpc-aaaaaaaa # REQUIRED. VPC ID of your existing Virtual Private Cloud (VPC)
      SSHCidrIp: "" # REQUIRED. The IP address range that can SSH to the EC2 instance (port: 22).
      HTTPCidrIp: "" # REQUIRED. The IP address range that can HTTP to the EC2 instance (port: 80).
      HTTPSCidrIp: "" # REQUIRED. The IP address range that can HTTPS to the EC2 instance (port: 443).

      # Network Interface Configuration
      PriManagementIP: "" # OPTIONAL. Private IP assigned to the Primary Management ENI (last octet has to be between 5 and 254). Leave empty for automatic assignment.
      PriManagementSubnet: subnet-aaaaaaaa # REQUIRED. SubnetId of an existing subnet in your Virtual Private Cloud (VPC) dedicated for Primary Management IP. NOTE - The Management Subnet CIDR should be different from that of VPC.
      PriClientIP: "" # OPTIONAL. Private IP assigned to the Primary Client ENI (last octet has to be between 5 and 254). Leave empty for automatic assignment.
      PriClientSubnet: subnet-bbbbbbbb # REQUIRED. SubnetId of an existing subnet in your Virtual Private Cloud (VPC) dedicated for Primary Client side
      PriServerIP: "" # OPTIONAL. Private IP assigned to the Primary Server ENI (last octet has to be between 5 and 254). Leave empty for automatic assignment.
      PriServerSubnet: subnet-cccccccc # REQUIRED. SubnetId of an existing subnet in your Virtual Private Cloud (VPC) dedicated for Primary Server side.
      SecManagementIP: "" # OPTIONAL. Private IP assigned to the Secondary Management ENI (last octet has to be between 5 and 254). Leave empty for automatic assignment.
      SecManagementSubnet: subnet-dddddddd # REQUIRED. SubnetId of an existing subnet in your Virtual Private Cloud (VPC) dedicated for Secondary Management IP
      SecClientIP: "" # OPTIONAL. Private IP assigned to the Secondary Client ENI (last octet has to be between 5 and 254). Leave empty for automatic assignment.
      SecClientSubnet: subnet-eeeeeeee # REQUIRED. SubnetId of an existing subnet in your Virtual Private Cloud (VPC) dedicated for Secondary Client side
      SecServerIP: "" # OPTIONAL. Private IP assigned to the Secondary Server ENI (last octet has to be between 5 and 254). Leave empty for automatic assignment.
      SecServerSubnet: subnet-ffffffff # REQUIRED. SubnetId of an existing subnet in your Virtual Private Cloud (VPC) dedicated for Secondary Server side.

      # Instance Configuration
      KeyName: "" # REQUIRED. Name of an existing EC2 KeyPair to enable SSH access to the instances
      InstanceType: m4.xlarge # OPTIONAL. Type of Citrix ADC instance. Default is  m4.xlarge. Refer choices.md for more.
      TenancyType: default # OPTIONAL. Choices [default|dedicated]. Tenancy Model.

  tasks:
    - name: Deploy Citrix ADC in HA pair mode Aross Availability Zones
      register: awscft
      cloudformation:
        stack_name: ha-across-AZ
        disable_rollback: yes
        template_url: "{{cft_url}}"
        region: "{{region}}"
        template_parameters: "{{cft_params}}"
        state: "{{state}}"
    - name: CFT details
      debug:
        var: awscft
        verbosity: "{{debug_verbosity}}"
