---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    state: present
    cft_url: "https://s3.amazonaws.com/netscaler-cft-templates/ha_3_nic_same_zone.template" # DO NOT change
    region: "" # Specify AWS Region
    debug_verbosity: 3 # use playbook with -vvv option to get the log message
    cft_params:
      # Citrix ADC Image
      pCitrixADCImageID: "" # OPTIONAL. AMI ID of Citrix ADC to be provisioned. If left empty, "Citrix ADC VPX - Customer Licensed Version 12.1-50.28 (https://aws.amazon.com/marketplace/pp/B00AA01BOE)" is provisioned by default

      # Virtual Private Network Configuration
      pVpcId: vpc-vvvvvvv # REQUIRED. VPC ID of your existing Virtual Private Cloud (VPC)
      pSSHCidrIp: "" # REQUIRED. The IP address range that can SSH to the EC2 instance (port: 22).
      pHTTPCidrIp: "" # REQUIRED. The IP address range that can HTTP to the EC2 instance (port: 80).
      pHTTPSCidrIp: "" # REQUIRED. The IP address range that can HTTPS to the EC2 instance (port: 443).

      # Network Interface Configuration
      pManagementIP: "" # OPTIONAL. Private IP assigned to the Primary Management ENI (last octet has to be between 5 and 254). Leave empty for automatic assignment.
      pManagementSubnet: subnet-aaaaaaa # REQUIRED. SubnetId of an existing subnet in your Virtual Private Cloud (VPC) dedicated for Management IPs. NOTE - The Management Subnet CIDR should be different from that of VPC.
      pClientIP: "" # OPTIONAL. Private IP assigned to the Client ENI (last octet has to be between 5 and 254). Leave empty for automatic assignment.
      pClientSubnet: subnet-bbbbbb # REQUIRED. SubnetId of an existing subnet in your Virtual Private Cloud (VPC) dedicated for Client side
      pServerIP: "" # OPTIONAL. Private IP assigned to the Server ENI (last octet has to be between 5 and 254). Leave empty for automatic assignment.
      pServerSubnet: subnet-ccccccc # REQUIRED. SubnetId of an existing subnet in your Virtual Private Cloud (VPC) dedicated for Server side.
      pManagementIPSec: "" # OPTIONAL. Private IP assigned to the Secondary Management ENI (last octet has to be between 5 and 254). Leave empty for automatic assignment.

      # Instance Configuration
      pKeyName: "" # REQUIRED. Name of an existing EC2 KeyPair to enable SSH access to the instances
      pInstanceType: m4.xlarge # OPTIONAL. Type of Citrix ADC instance. Default is  m4.xlarge. Refer choices.md for more.
      pTenancyType: default # OPTIONAL. Choices [default|dedicated]. Tenancy Model.
      PublishCloudwatchMetrics: "Yes" # OPTIONAL. Enter "Yes" (within quotes) to enable publishing of VPX metrics to Cloudwatch, or "No" (within quotes) to disable publishing.

  tasks:
    - name: Deploy Citrix ADC in HA pair mode in the same Availability Zones
      register: awscft
      cloudformation:
        stack_name: ha-same-AZ
        disable_rollback: yes
        template_url: "{{cft_url}}"
        region: "{{region}}"
        template_parameters: "{{cft_params}}"
        state: "{{state}}"
    - name: CFT details
      debug:
        var: awscft
        verbosity: "{{debug_verbosity}}"
