---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    state: present
    cft_url: "https://s3.amazonaws.com/citrixadc-automation/license-cft-HA-3nic-Across-AZ.template" # DO NOT change
    region: "" # Specify AWS Region
    debug_verbosity: 3 # use playbook with -vvv option to get the log message
    cft_params:
      # Virtual Private Network Configuration
      pVpcId: vpc-aaaaaaaa # REQUIRED. VPC ID of your existing Virtual Private Cloud (VPC)
      pSSHCidrIp: "" # REQUIRED. The IP address range that can SSH to the EC2 instance (port: 22).
      pHTTPCidrIp: "" # REQUIRED. The IP address range that can HTTP to the EC2 instance (port: 80).
      pHTTPSCidrIp: "" # REQUIRED. The IP address range that can HTTPS to the EC2 instance (port: 443).

      # Network Interface Configuration
      pPriManagementIP: "" # OPTIONAL. Private IP assigned to the Primary Management ENI (last octet has to be between 5 and 254). Leave empty for automatic assignment.
      pPriManagementSubnet: subnet-aaaaaaaa # REQUIRED. SubnetId of an existing subnet in your Virtual Private Cloud (VPC) dedicated for Primary Management IP. NOTE - The Management Subnet CIDR should be different from that of VPC.
      pPriClientIP: "" # OPTIONAL. Private IP assigned to the Primary Client ENI (last octet has to be between 5 and 254). Leave empty for automatic assignment.
      pPriClientSubnet: subnet-bbbbbbbb # REQUIRED. SubnetId of an existing subnet in your Virtual Private Cloud (VPC) dedicated for Primary Client side
      pPriServerIP: "" # OPTIONAL. Private IP assigned to the Primary Server ENI (last octet has to be between 5 and 254). Leave empty for automatic assignment.
      pPriServerSubnet: subnet-cccccccc # REQUIRED. SubnetId of an existing subnet in your Virtual Private Cloud (VPC) dedicated for Primary Server side.
      pSecManagementIP: "" # OPTIONAL. Private IP assigned to the Secondary Management ENI (last octet has to be between 5 and 254). Leave empty for automatic assignment.
      pSecManagementSubnet: subnet-dddddddd # REQUIRED. SubnetId of an existing subnet in your Virtual Private Cloud (VPC) dedicated for Secondary Management IP
      pSecClientIP: "" # OPTIONAL. Private IP assigned to the Secondary Client ENI (last octet has to be between 5 and 254). Leave empty for automatic assignment.
      pSecClientSubnet: subnet-eeeeeeee # REQUIRED. SubnetId of an existing subnet in your Virtual Private Cloud (VPC) dedicated for Secondary Client side
      pSecServerIP: "" # OPTIONAL. Private IP assigned to the Secondary Server ENI (last octet has to be between 5 and 254). Leave empty for automatic assignment.
      pSecServerSubnet: subnet-ffffffff # REQUIRED. SubnetId of an existing subnet in your Virtual Private Cloud (VPC) dedicated for Secondary Server side.

      # Instance Configuration
      pKeyName: "" # REQUIRED. Name of an existing EC2 KeyPair to enable SSH access to the instances
      pInstanceType: m4.xlarge # OPTIONAL. Type of Citrix ADC instance. Default is  m4.xlarge. Refer choices.md for more.
      pTenancyType: default # OPTIONAL. Choices [default|dedicated]. Tenancy Model.

      # Licence Server Details
      pADMIP: "" # REQUIRED. Reachable ADM / ADM Agent IP

      # License Details
      pLicensingMode: "" # REQUIRED.Choices [Pooled-Licensing|CICO-Licensing|VCPU-Licensing]. Select the Licensing Mode

      # Pooled Licensing Details (Select only when the above Licensing Mode is "Pooled-Licensing")
      pBandwidth: 0 # CONDITIONAL. If pLicencingMode is Pooled-Licensing. Initial bandwidth of the license in Mbps to be allocated after BYOL ADCs are created. Should be multiple of 10 Mbps. Default is 0 Mbps
      pPooledEdition: "" # CONDITIONAL. Choices [Standard|Advanced|Premium]. If pLicencingMode is Pooled-Licensing. License Edition for Pooled Capacity Licensing Mode

      # CICO Licensing Details (Select only when the above Licensing Mode is "CICO-Licensing")
      pPlatform: "" # CONDITIONAL. If pLicencingMode is CICO-Licensing. License Platform. Refer choices.md for more.

      # VCPU Licensing Details (Select only when the above Licensing Mode is "CPU-Licensing")
      pVCPUEdition: "" # CONDITIONAL. Choices [Standard|Advanced|Premium]. If pLicencingMode is VCPU-Licensing. License Edition for vCPU Licensing Mode

  tasks:
    - name: Deploy BYOL Citrix ADCs in HA mode Across Availability Zones and allocate user defined license
      register: awscft
      cloudformation:
        stack_name: ha-across-AZ
        disable_rollback: yes
        template_url: "{{cft_url}}"
        region: "{{region}}"
        template_parameters: "{{cft_params}}"
        state: "{{state}}"
    - name: Stack details
      debug:
        var: awscft
        verbosity: "{{debug_verbosity}}"
